.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. CleanCoin_qt test_CleanCoin_qt
clean: FORCE
	$(MAKE) -C .. CleanCoin_qt_clean test_CleanCoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_CleanCoin_qt_check
CleanCoin-qt CleanCoin-qt.exe: FORCE
	 $(MAKE) -C .. CleanCoin_qt
